import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { cls } from "@/utils/tailwind/cls";
import Navbar from "@/components/nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cls(
					inter.className,
					`text-text bg-background p-2 pb-16 pl-2 sm:pb-2 sm:pl-16 md:px-32 min-h-screen`
				)}
			>
				<header>
					<Navbar />
				</header>
				<main className={cls(``)}>{children}</main>
				<footer></footer>
			</body>
		</html>
	);
}
